<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map([
  '__library_version__' => 2,
  'class'               => [
    'ComposerLinter'     => 'composer_linter/src/ComposerLinter.php',
    'JestUnitTestEngine' => 'jest_unit_test_engine/src/JestUnitTestEngine.php',
    'MultiTestEngine'    => 'multi_test_engine/src/MultiTestEngine.php',
    'PhpstanLinter'      => 'phpstan_linter/src/PhpstanLinter.php',
  ],
  'function' => [],
  'xmap'     => [
    'ComposerLinter'     => 'ArcanistExternalLinter',
    'JestUnitTestEngine' => 'ArcanistUnitTestEngine',
    'MultiTestEngine'    => 'ArcanistUnitTestEngine',
    'PhpstanLinter'      => 'ArcanistLinter',
  ],
]);
